import 'package:equatable/equatable.dart';

/// Represents a single telemetry log entry generated by BLE events.
class BleLogEntry extends Equatable {
  const BleLogEntry({
    required this.timestamp,
    required this.message,
    required this.level,
    this.deviceId,
  });

  /// Recreate a log entry from JSON.
  factory BleLogEntry.fromJson(Map<String, dynamic> json) {
    return BleLogEntry(
      timestamp: DateTime.parse(json['timestamp'] as String),
      message: json['message'] as String,
      level: json['level'] as String,
      deviceId: json['deviceId'] as String?,
    );
  }

  /// The exact time when the log was captured.
  final DateTime timestamp;

  /// The text content describing the event.
  final String message;

  /// Severity level of the log (e.g. INFO, WARN, ERROR, DEBUG).
  final String level;

  /// The remote peripheral ID associated with the event, if applicable.
  final String? deviceId;

  /// Map log entry into JSON format for storage.
  Map<String, dynamic> toJson() {
    return {
      'timestamp': timestamp.toIso8601String(),
      'message': message,
      'level': level,
      'deviceId': deviceId,
    };
  }

  @override
  List<Object?> get props => [timestamp, message, level, deviceId];
}
